server:
  port: 8089
spring:
  application:
    name=ETL
  datasource:
    url: jdbc:postgresql://localhost:5432/etl
    username: admin
    password: password
file:
  download:
    cnes-url: ${CNES_URL}
    sigtap-url: ${SIGTAP_URL}